# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
default: &default
  adapter: mysql2
  pool: 25
  timeout: 5000
  encoding: utf8mb4
  collation: utf8mb4_bin

development:
  <<: *default
  database: db_cache
  username: root
  password: '123456'
